# Generated by Django 4.2.5 on 2023-09-27 18:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
